# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [68]:
# The code goes here
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [16]:
arr1 = np.ones((1, 1, 10)) 
print(arr1)

arr2 = np.arange(1, 20, 1, dtype = "int")
print(arr2)

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [20]:
arr3 = np.random.rand(3, 3, 3)
print(arr3)

arr3a = arr3.reshape(27)
print(arr3a)

[[[0.56120219 0.55829373 0.79163606]
  [0.40754831 0.59487149 0.14306196]
  [0.18117001 0.81807682 0.77122624]]

 [[0.68673714 0.47554808 0.13772342]
  [0.95031447 0.43016711 0.75984853]
  [0.16513715 0.78915555 0.90829122]]

 [[0.9514406  0.96613975 0.11451089]
  [0.67165576 0.89078754 0.33603242]
  [0.81249109 0.99881588 0.32993606]]]
[0.56120219 0.55829373 0.79163606 0.40754831 0.59487149 0.14306196
 0.18117001 0.81807682 0.77122624 0.68673714 0.47554808 0.13772342
 0.95031447 0.43016711 0.75984853 0.16513715 0.78915555 0.90829122
 0.9514406  0.96613975 0.11451089 0.67165576 0.89078754 0.33603242
 0.81249109 0.99881588 0.32993606]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [24]:
arr4 = np.linspace(1, 10, 20, dtype = "float16")
print(arr4)

[ 1.     1.474  1.947  2.422  2.895  3.37   3.842  4.316  4.79   5.26
  5.74   6.21   6.684  7.156  7.633  8.1    8.58   9.055  9.52  10.   ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [29]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [27]:
20

20

In [37]:
print(a[1:5,3:5])

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [39]:
print(a[1])

[ 6  7  8  9 10]


```python
array([ 6,  7,  8,  9, 10])
```

In [41]:
print(a[3, 4])

20


## 2.5 

Calculate the sum of all the numbers in `a`.

In [42]:
sum_a = np.sum(a)
print(sum_a)

325


## 2.6 

Calculate the sum of each row in `a`.

In [43]:
sum_row0 = np.sum(a[0])
print(sum_row0)

15


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [45]:
print(325/25)

a_bool = a > 13
print(a_bool)

13.0
[[False False False False False]
 [False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [3]:
import pandas as pd 

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [4]:
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"
df = pd.read_csv(url, sep=",", header = 0)

print(df.head(5))

     country food_category  consumption  co2_emmission
0  Argentina          Pork        10.51          37.20
1  Argentina       Poultry        38.66          41.53
2  Argentina          Beef        55.48        1712.00
3  Argentina   Lamb & Goat         1.56          54.63
4  Argentina          Fish         4.36           6.96


## 2.10 

How many rows and columns are there in the dataframe?

In [5]:
print("The data frame has this many rows:") 
print(len(df))

df.shape

The data frame has this many rows:
1430


(1430, 4)

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [6]:
df.columns

Index(['country', 'food_category', 'consumption', 'co2_emmission'], dtype='object')

In [74]:


co2_mean = df["co2_emmission"].mean()
print(co2_mean)

74.383993006993


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [83]:
co2_max = df["co2_emmission"].max()
print(co2_max)

food_stats = pd.DataFrame()
food_stats = df.groupby("country")["co2_emmission"].max()
food_stats = df.groupby("food_category")["co2_emmission"].max()
food_stats


1712.0


food_category
Beef                        1712.00
Eggs                          17.59
Fish                         286.94
Lamb & Goat                  739.62
Milk - inc. cheese           613.57
Nuts inc. Peanut Butter       40.76
Pork                         237.54
Poultry                       67.14
Rice                         219.76
Soybeans                       7.63
Wheat and Wheat Products      37.66
Name: co2_emmission, dtype: float64

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

## 2.14

Which country consumes the least amount of beef per person per year?


In [ ]:
# code comes here

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [ ]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.